[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/*"
  to = "http://localhost:8000/:splat"
  status = 200
  force = true

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3000
  autoLaunch = false
